### ISSUE TITLE
Blurred 32px images

### ISSUE THREAD

**Issue by spongeabc5** [TheMachinumps/Advanced-badge-editor#2]
Images imported from PNGs are fine in the 64px images, but are blurred in the downsized 32px images and on the HOME Menu. This is most noticeable with the Pixel Collection badges, for example, importing this image into the program:
![imported image](https://cloud.githubusercontent.com/assets/25075034/21883314/52b95372-d863-11e6-897a-3d4a6af70068.png)
results in these images:
![image](https://cloud.githubusercontent.com/assets/25075034/21883376/ab2ee7ec-d863-11e6-8985-0fab37bc6b36.png)

**Comment by AntiMach** [comment]
The way images are downscaled may make images blurry. I will be sure to add another option for downscaling Pixel badges
